1.Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.
2. Apply functions
1. Concatenation
2.Any
3.Shape
4. Reshape
5.Append
6.Extend


In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
num_elements=arr.size

In [ ]:
elements_bytes=arr.itemsize

In [ ]:
total_bytes=arr.nbytes

In [ ]:
print("Number of elements:", num_elements)


Number of elements: 5


In [ ]:
print("Length of one array element in bytes:", elements_bytes)


Length of one array element in bytes: 8


In [ ]:
print("Total bytes consumed by the elements:", total_bytes)

Total bytes consumed by the elements: 40


In [ ]:
arr1=np.array([3,4,5])
arr2=np.array([9,7,1])

In [ ]:
concatenate_arr=np.concatenate((arr1,arr2))

In [ ]:
concatenate_arr

array([3, 4, 5, 9, 7, 1])

In [ ]:
arr3 = np.array([False, False, True])
print("Any function result:", np.any(arr3))
print("Shape of the array:", arr.shape)

Any function result: True
Shape of the array: (5,)


In [ ]:
arr4 = np.arange(6)
reshaped = arr4.reshape(2, 3)
print("Reshaped array:")
print(reshaped)

Reshaped array:
[[0 1 2]
 [3 4 5]]


In [ ]:
arr5 = np.array([1, 2, 3])
appended = np.append(arr5, 4)
print("Appended array:", appended)

Appended array: [1 2 3 4]


In [ ]:
arr6 = np.array([1, 2, 3])
arr7 = np.array([4, 5, 6])
extended = np.concatenate((arr6, arr7))
print("Extended array:", extended)

Extended array: [1 2 3 4 5 6]
